// Transcribed source records for the one-time resident source-notes
// import. Every field here is a direct transcription of what was
// photographed — nothing here infers a fact the source text doesn't
// state. See the routing/destination decisions this script applies in
// scripts/importResidentSourceNotes.ts and its module comment for the
// governing rules.
import type { Source1Record, Source2Record } from "./types.ts";

export const SOURCE_1_ID = "resident_service_needs_photo_2026_07" as const;
export const SOURCE_2_ID = "watermere_whiteboard_photo_2026_06_07" as const;

export const SOURCE_1_RECORDS: readonly Source1Record[] = [
  {
    kind: "needs_sheet",
    sourceId: SOURCE_1_ID,
    recordIndex: 1,
    apartment: "7313",
    residentNames: ["Jerald Maxwell", "Elizabeth Maxwell"],
    needs: ["TV assistance", "medication reminders", "walker assistance", "bathroom assistance"],
    transcriptionNote:
      "Shared apartment/couple entry. Needs are not individually attributed between Jerald and Elizabeth in the source. Do not write to Current Needs for either resident without attribution; record as a shared Working Note on both, flagged for individual-assignment verification.",
  },
  {
    kind: "needs_sheet",
    sourceId: SOURCE_1_ID,
    recordIndex: 2,
    apartment: "10201",
    residentNames: ["Carolyn Rikee"],
    needs: ["help using remote", "TV assistance", "phone assistance", "walker assistance"],
  },
  {
    kind: "needs_sheet",
    sourceId: SOURCE_1_ID,
    recordIndex: 3,
    apartment: "6304",
    residentNames: ["Bobbie Burkett"],
    needs: ["TV and remote assistance", "meal assistance at times", "medication reminders"],
  },
  {
    kind: "needs_sheet",
    sourceId: SOURCE_1_ID,
    recordIndex: 4,
    apartment: "8301",
    residentNames: ["Kathryn Morshed"],
    needs: [
      "medication reminders",
      "shower assistance",
      "TV assistance",
      "washing machine assistance",
      "air-conditioning and heat assistance",
      "walker assistance",
      "help finding apartment",
    ],
  },
  {
    kind: "needs_sheet",
    sourceId: SOURCE_1_ID,
    recordIndex: 5,
    apartment: "9310",
    residentNames: ["Marion White"],
    needs: ["TV assistance", "washing machine assistance", "help with calls", "help with mail"],
  },
  {
    kind: "needs_sheet",
    sourceId: SOURCE_1_ID,
    recordIndex: 6,
    apartment: "10307",
    residentNames: ["Barbara Schmid"],
    needs: ["walker assistance", "cannot walk without walker"],
    transcriptionNote:
      "Preserve 'cannot walk without walker' as a source-stated mobility limitation only. Do not add a diagnosis or fall-risk classification.",
  },
  {
    kind: "needs_sheet",
    sourceId: SOURCE_1_ID,
    recordIndex: 7,
    apartment: "6306",
    residentNames: ["Ada Washington"],
    needs: ["menu reminders", "reminders of the time", "reminders of the day of the week"],
    transcriptionNote: "Do not infer dementia or any cognitive diagnosis.",
  },
  {
    kind: "needs_sheet",
    sourceId: SOURCE_1_ID,
    recordIndex: 8,
    apartment: "6308",
    residentNames: ["Janice Seiden"],
    needs: ["medication reminders", "food drop-off", "leg issues"],
    originalWording: "legs are bad",
    transcriptionNote:
      "Preserve original wording in spirit: 'Resident reportedly has significant leg issues.' Do not infer a diagnosis.",
  },
  {
    kind: "needs_sheet",
    sourceId: SOURCE_1_ID,
    recordIndex: 9,
    apartment: "7204",
    residentNames: ["Brenda Fritschen"],
    needs: [
      "help finding apartment",
      "medication reminders",
      "scooter assistance",
      "walker assistance",
      "reminders and help locating items",
    ],
  },
  {
    kind: "needs_sheet",
    sourceId: SOURCE_1_ID,
    recordIndex: 10,
    apartment: "9301",
    residentNames: ["Kathryn Brown"],
    needs: ["phone assistance", "internet assistance", "washing machine assistance"],
  },
  {
    kind: "needs_sheet",
    sourceId: SOURCE_1_ID,
    recordIndex: 11,
    apartment: "9306",
    residentNames: ["Virginia Wynn"],
    needs: ["help getting off scooter", "assistance getting to the table"],
  },
];

export const SOURCE_2_RECORDS: readonly Source2Record[] = [
  {
    kind: "whiteboard",
    sourceId: SOURCE_2_ID,
    recordIndex: 1,
    personLabel: "Johnny and Lajuana",
    proposedDays: "Monday through Sunday",
    proposedTimes: ["8:00 AM", "12:00 PM", "5:00 PM"],
    frequency: "3 times per day",
    need: "dining escort",
    destinations: ["relationship_working_note", "service_opportunity"],
    doNotInferNote: "Do not match on first names alone if more than one candidate exists for either name.",
  },
  {
    kind: "whiteboard",
    sourceId: SOURCE_2_ID,
    recordIndex: 2,
    personLabel: "Virginia Wynn",
    proposedDays: "Wednesday, Friday",
    proposedDuration: "2 hours",
    contextNote: "Louise King, daughter, said the resident is staying with the current caregiver for now.",
    destinations: ["timeline_or_dated_note", "relationship_working_note"],
    doNotInferNote: "Do not mark any service active.",
  },
  {
    kind: "whiteboard",
    sourceId: SOURCE_2_ID,
    recordIndex: 3,
    personLabel: "Brenda Fritschen",
    need: "medication reminders",
    frequency: "twice daily",
    contextNote: "Schedule TBD.",
    destinations: ["current_needs_reinforce", "relationship_working_note"],
    doNotInferNote: "No scheduled times should be invented.",
  },
  {
    kind: "whiteboard",
    sourceId: SOURCE_2_ID,
    recordIndex: 4,
    personLabel: "E. Goldberg",
    apartmentHint: "6703",
    apartmentHintConfidence: "low",
    proposedDays: "Monday through Sunday",
    proposedTimes: ["8:00 AM to 10:00 AM", "7:30 PM to 8:50 PM"],
    statusNote:
      "Status: starting per approval. In rehab until approximately July 1 through July 8. Then may need 24/7 care for a few days.",
    destinations: ["timeline_or_dated_note", "relationship_working_note"],
    doNotInferNote: "Do not mark current, approved, or active without corroborating live data.",
  },
  {
    kind: "whiteboard",
    sourceId: SOURCE_2_ID,
    recordIndex: 5,
    personLabel: "L. Kaplan",
    proposedDays: "Monday through Sunday",
    proposedDuration: "12 hours daily",
    proposedTimes: ["10:30 AM to 10:30 PM"],
    historicalNote: "Coming on 6/29.",
    destinations: ["timeline_or_dated_note", "relationship_working_note"],
    doNotInferNote: "Do not mark active without corroboration.",
  },
  {
    kind: "whiteboard",
    sourceId: SOURCE_2_ID,
    recordIndex: 6,
    personLabel: "Mick",
    proposedDays: "Tuesday, Thursday",
    proposedTimes: ["Tuesday 1:00 PM to 4:00 PM", "Thursday 1:00 PM to 4:00 PM"],
    destinations: ["relationship_working_note"],
    doNotInferNote: "Insufficient resident identity. Skip and report if not uniquely resolvable.",
  },
  {
    kind: "whiteboard",
    sourceId: SOURCE_2_ID,
    recordIndex: 7,
    personLabel: "John",
    proposedDays: "Monday through Sunday",
    proposedTimes: ["8:00 AM", "8:00 PM"],
    need: "medication reminder",
    destinations: ["relationship_working_note"],
    doNotInferNote: "Insufficient resident identity. Skip and report if not uniquely resolvable.",
  },
  {
    kind: "whiteboard",
    sourceId: SOURCE_2_ID,
    recordIndex: 8,
    personLabel: "B. Powers",
    proposedDays: "Friday",
    proposedTimes: ["1:00 PM to 5:00 PM"],
    contextNote: "Ed planned to get back to Serve after a July 3 visit with his son.",
    destinations: ["timeline_or_dated_note", "relationship_working_note"],
    doNotInferNote: "Do not assume service began.",
  },
  {
    kind: "whiteboard",
    sourceId: SOURCE_2_ID,
    recordIndex: 9,
    personLabel: "A. Nickell",
    proposedDays: "Tuesday, Friday",
    proposedTimes: ["9:00 AM to 1:00 PM"],
    contextNote: "Has a caregiver.",
    destinations: ["relationship_working_note"],
    doNotInferNote: "Do not create an active service schedule.",
  },
  {
    kind: "whiteboard",
    sourceId: SOURCE_2_ID,
    recordIndex: 10,
    personLabel: "J. Gould",
    apartmentHint: "3405",
    apartmentHintConfidence: "medium",
    frequency: "once per week",
    proposedDuration: "1 hour",
    need: "laundry",
    contextNote: "Additional known context may already exist in Serve intake records under Jerry Gould.",
    destinations: ["current_needs_reinforce", "service_opportunity", "relationship_working_note"],
  },
  {
    kind: "whiteboard",
    sourceId: SOURCE_2_ID,
    recordIndex: 11,
    personLabel: "B. Welch",
    proposedDays: "Friday",
    frequency: "once per week",
    proposedDuration: "4 hours",
    contextNote: "Has a caregiver.",
    destinations: ["relationship_working_note", "service_opportunity"],
    doNotInferNote: "Do not mark Serve service active.",
  },
  {
    kind: "whiteboard",
    sourceId: SOURCE_2_ID,
    recordIndex: 12,
    personLabel: "Kathryn Morshed",
    proposedDays: "Monday through Friday",
    proposedDuration: "20 minutes",
    need: "medication reminders, linens, housekeeping",
    destinations: ["current_needs_reinforce", "service_opportunity", "relationship_working_note"],
  },
  {
    kind: "whiteboard",
    sourceId: SOURCE_2_ID,
    recordIndex: 13,
    personLabel: "D. Kakazu",
    proposedDays: "Monday through Sunday",
    frequency: "one hour morning and evening for reminders; approximately two hours once weekly for bathing",
    destinations: [],
    synthenticDataPolicyFlag: true,
    doNotInferNote:
      "Doris Kakazu was previously identified as synthetic test data (her relationships, wellness follow-ups, working notes, and full Current Needs history were removed). Her residents row itself was never deleted, per docs/engineering/TEST_DATA_HYGIENE.md. Treat as policy-skipped pending explicit confirmation that a legitimate, independent live resident record exists.",
  },
  {
    kind: "whiteboard",
    sourceId: SOURCE_2_ID,
    recordIndex: 14,
    personLabel: "A. Campbell",
    contextNote: "Needs 24/7 support. Interested in companion care. Would like to go on walks.",
    historicalNote: "Possible meeting around July 2.",
    destinations: ["resident_working_note", "timeline_or_dated_note"],
    sourceTextUncertain: true,
    doNotInferNote:
      "Additional handwriting partially illegible — not converted into facts. Do not infer exact walking times, temperatures, family participants, or approval status.",
  },
];
