import type { Prospect } from "@/lib/supabase/types";

export const COMMUNITY = {
  name: "Watermere at Frisco",
  totalResidents: 320,
  serveClients: 3,
  activeProspects: 14,
  requiresFollowUp: 10,
  pendingAssessments: 3,
  familiesAwaitingProposal: 2,
  birthdaysThisWeek: 4,
  wellnessChecksDue: 8,
  formerClients: 5,
} as const;

export const RESIDENT_TAB_COUNTS: Record<string, number> = {
  all:            COMMUNITY.totalResidents,
  wellness_watch: COMMUNITY.wellnessChecksDue,
  prospects:      COMMUNITY.activeProspects,
  active_clients: COMMUNITY.serveClients,
  former_clients: COMMUNITY.formerClients,
};

export const DEMO_SCHEDULE = [
  { time: "8:00 AM",  client: "Margaret Chen",  service: "Personal Care",    caregiver: "Sarah M.", location: "Apt 2105",  status: "active"   as const },
  { time: "10:30 AM", client: "Robert Williams", service: "Companionship",    caregiver: "James T.", location: "Apt 10332", status: "active"   as const },
  { time: "1:00 PM",  client: "Dorothy Baker",   service: "Specialized Care", caregiver: "Maria L.", location: "Apt 8415",  status: "upcoming" as const },
  { time: "3:30 PM",  client: "James Morrison",  service: "Personal Care",    caregiver: "Kevin S.", location: "Apt 6320",  status: "upcoming" as const },
];

export const DEMO_STARTING_THIS_WEEK = [
  { name: "Helen Carter", start: "Monday",    initials: "HC" },
  { name: "Thomas Reid",  start: "Wednesday", initials: "TR" },
];

export const DEMO_PROSPECTS: Prospect[] = [
  // ─── Active Clients (3) — status: converted ─────────────────────────────
  {
    id: "demo-client-001",
    created_at: "2026-03-15T10:00:00Z",
    status: "converted",
    source: "community_liaison",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Margaret",
    resident_last_name: "Chen",
    resident_relationship: "parent",
    contact_first_name: "Jennifer",
    contact_last_name: "Chen",
    contact_phone: "(214) 555-0142",
    contact_email: "j.chen@email.com",
    support_type: "home_care",
    start_timing: "coming_weeks",
    care_needs:
      "Margaret requires morning personal care assistance including bathing, dressing, and medication management. She is independent in other daily activities and enjoys socializing in the common areas.",
    referral_source: "staff_referral",
    consent_given: true,
    raw_submission: { community: "Apt 2105" },
  },
  {
    id: "demo-client-002",
    created_at: "2026-03-22T14:30:00Z",
    status: "converted",
    source: "website",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Robert",
    resident_last_name: "Williams",
    resident_relationship: "spouse",
    contact_first_name: "Patricia",
    contact_last_name: "Williams",
    contact_phone: "(972) 555-0318",
    contact_email: "pat.williams@email.com",
    support_type: "concierge",
    start_timing: "coming_weeks",
    care_needs:
      "Robert benefits from daily companionship visits and errand assistance. His wife Patricia is his primary caregiver and appreciates support on her away days.",
    referral_source: "family_referral",
    consent_given: true,
    raw_submission: { community: "Apt 10332" },
  },
  {
    id: "demo-client-003",
    created_at: "2026-04-01T09:00:00Z",
    status: "converted",
    source: "community_liaison",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Dorothy",
    resident_last_name: "Baker",
    resident_relationship: "parent",
    contact_first_name: "Michael",
    contact_last_name: "Baker",
    contact_phone: "(469) 555-0284",
    contact_email: "mbaker@email.com",
    support_type: "geriatric",
    start_timing: "coming_weeks",
    care_needs:
      "Dorothy has early-stage memory concerns and benefits from structured daily visits, cognitive engagement activities, and regular wellness check-ins coordinated with her physician.",
    referral_source: "doctor_referral",
    consent_given: true,
    raw_submission: { community: "Apt 8415" },
  },

  // ─── Former Clients (5) — status: closed ────────────────────────────────
  {
    id: "demo-former-001",
    created_at: "2025-10-08T11:00:00Z",
    status: "closed",
    source: "community_liaison",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Helen",
    resident_last_name: "Carter",
    resident_relationship: "parent",
    contact_first_name: "Susan",
    contact_last_name: "Carter",
    contact_phone: "(214) 555-0801",
    contact_email: "scarter@email.com",
    support_type: "home_care",
    start_timing: "coming_weeks",
    care_needs: null,
    referral_source: "staff_referral",
    consent_given: true,
    raw_submission: { community: "Apt 1204" },
  },
  {
    id: "demo-former-002",
    created_at: "2025-11-14T09:30:00Z",
    status: "closed",
    source: "website",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Thomas",
    resident_last_name: "Reid",
    resident_relationship: "parent",
    contact_first_name: "David",
    contact_last_name: "Reid",
    contact_phone: "(972) 555-0412",
    contact_email: null,
    support_type: "concierge",
    start_timing: "coming_weeks",
    care_needs: null,
    referral_source: "family_referral",
    consent_given: true,
    raw_submission: { community: "Apt 3318" },
  },
  {
    id: "demo-former-003",
    created_at: "2025-09-20T15:00:00Z",
    status: "closed",
    source: "community_liaison",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Eleanor",
    resident_last_name: "Simmons",
    resident_relationship: "parent",
    contact_first_name: "Mark",
    contact_last_name: "Simmons",
    contact_phone: "(469) 555-0923",
    contact_email: null,
    support_type: "home_care",
    start_timing: "future",
    care_needs: null,
    referral_source: null,
    consent_given: true,
    raw_submission: { community: "Apt 0612" },
  },
  {
    id: "demo-former-004",
    created_at: "2025-12-01T10:00:00Z",
    status: "closed",
    source: "community_liaison",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Bernard",
    resident_last_name: "Walsh",
    resident_relationship: "spouse",
    contact_first_name: "Catherine",
    contact_last_name: "Walsh",
    contact_phone: "(214) 555-0677",
    contact_email: null,
    support_type: "geriatric",
    start_timing: "coming_weeks",
    care_needs: null,
    referral_source: "doctor_referral",
    consent_given: true,
    raw_submission: { community: "Apt 2204" },
  },
  {
    id: "demo-former-005",
    created_at: "2025-08-15T13:00:00Z",
    status: "closed",
    source: "website",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Marian",
    resident_last_name: "Kowalski",
    resident_relationship: "parent",
    contact_first_name: "Peter",
    contact_last_name: "Kowalski",
    contact_phone: "(972) 555-0558",
    contact_email: "p.kowalski@email.com",
    support_type: "home_care",
    start_timing: "not_sure",
    care_needs: null,
    referral_source: "family_referral",
    consent_given: true,
    raw_submission: { community: "Apt 1905" },
  },

  // ─── Active Prospects (13) — 8 with immediately → Wellness Watch ────────
  {
    id: "demo-prospect-001",
    created_at: "2026-06-10T09:15:00Z",
    status: "assessment_scheduled",
    source: "community_liaison",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "James",
    resident_last_name: "Morrison",
    resident_relationship: "parent",
    contact_first_name: "Carol",
    contact_last_name: "Morrison",
    contact_phone: "(214) 555-0360",
    contact_email: "carol.morrison@email.com",
    support_type: "home_care",
    start_timing: "immediately",
    care_needs:
      "James has had two recent falls and his family is concerned about his safety. He needs daily check-ins and assistance with bathing and mobility.",
    referral_source: "staff_referral",
    consent_given: true,
    raw_submission: { community: "Apt 6320" },
  },
  {
    id: "demo-prospect-002",
    created_at: "2026-06-12T11:00:00Z",
    status: "assessment_scheduled",
    source: "community_liaison",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Frances",
    resident_last_name: "Kimball",
    resident_relationship: "parent",
    contact_first_name: "Alice",
    contact_last_name: "Kimball",
    contact_phone: "(972) 555-0291",
    contact_email: null,
    support_type: "concierge",
    start_timing: "immediately",
    care_needs:
      "Frances lives alone and her daughter is worried about her increasing isolation. She would benefit from companionship visits and help with errands.",
    referral_source: "staff_referral",
    consent_given: true,
    raw_submission: { community: "Apt 0742" },
  },
  {
    id: "demo-prospect-003",
    created_at: "2026-06-14T08:30:00Z",
    status: "reviewing",
    source: "website",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Arthur",
    resident_last_name: "Haines",
    resident_relationship: "spouse",
    contact_first_name: "Ruth",
    contact_last_name: "Haines",
    contact_phone: "(469) 555-0114",
    contact_email: "ruth.haines@email.com",
    support_type: "home_care",
    start_timing: "immediately",
    care_needs:
      "Arthur recently returned from a short-term rehabilitation stay. His wife Ruth manages most of his care but needs morning support for bathing and medication.",
    referral_source: "family_referral",
    consent_given: true,
    raw_submission: { community: "Apt 3507" },
  },
  {
    id: "demo-prospect-004",
    created_at: "2026-06-15T14:00:00Z",
    status: "contacted",
    source: "community_liaison",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Stanley",
    resident_last_name: "Morton",
    resident_relationship: "parent",
    contact_first_name: "Barbara",
    contact_last_name: "Morton",
    contact_phone: "(214) 555-0732",
    contact_email: null,
    support_type: "home_care",
    start_timing: "immediately",
    care_needs:
      "Stanley has diabetes and requires assistance with medication management and daily vitals monitoring. His daughter lives out of state and is seeking reliable local support.",
    referral_source: "doctor_referral",
    consent_given: true,
    raw_submission: { community: "Apt 2218" },
  },
  {
    id: "demo-prospect-005",
    created_at: "2026-06-16T10:45:00Z",
    status: "contacted",
    source: "community_liaison",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Louise",
    resident_last_name: "Patterson",
    resident_relationship: "parent",
    contact_first_name: "Kevin",
    contact_last_name: "Patterson",
    contact_phone: "(972) 555-0485",
    contact_email: "kpatterson@email.com",
    support_type: "geriatric",
    start_timing: "immediately",
    care_needs:
      "Louise has moderate dementia and her son is concerned about memory-related safety. Seeking geriatric care management and structured daily routines.",
    referral_source: "staff_referral",
    consent_given: true,
    raw_submission: { community: "Apt 1543" },
  },
  {
    id: "demo-prospect-006",
    created_at: "2026-06-17T09:00:00Z",
    status: "reviewing",
    source: "website",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Vivienne",
    resident_last_name: "Cole",
    resident_relationship: "parent",
    contact_first_name: "Daniel",
    contact_last_name: "Cole",
    contact_phone: "(469) 555-0627",
    contact_email: null,
    support_type: "concierge",
    start_timing: "immediately",
    care_needs:
      "Vivienne recently lost her driver's license and needs transportation assistance and concierge support for medical appointments and errands.",
    referral_source: "family_referral",
    consent_given: true,
    raw_submission: { community: "Apt 2104" },
  },
  {
    id: "demo-prospect-007",
    created_at: "2026-06-18T15:30:00Z",
    status: "new",
    source: "community_liaison",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Theodore",
    resident_last_name: "Larson",
    resident_relationship: "parent",
    contact_first_name: "Claire",
    contact_last_name: "Larson",
    contact_phone: "(214) 555-0943",
    contact_email: "claire.larson@email.com",
    support_type: "home_care",
    start_timing: "immediately",
    care_needs:
      "Theodore's daughter submitted an inquiry after he had a fall in his apartment. Needs immediate review and outreach.",
    referral_source: "staff_referral",
    consent_given: true,
    raw_submission: { community: "Apt 4501" },
  },
  {
    id: "demo-prospect-008",
    created_at: "2026-06-20T08:00:00Z",
    status: "new",
    source: "website",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Miriam",
    resident_last_name: "Goldstein",
    resident_relationship: "parent",
    contact_first_name: "Steven",
    contact_last_name: "Goldstein",
    contact_phone: "(972) 555-0176",
    contact_email: "s.goldstein@email.com",
    support_type: "geriatric",
    start_timing: "immediately",
    care_needs:
      "Miriam has Parkinson's and her family is exploring geriatric care management options. Website inquiry received this week.",
    referral_source: null,
    consent_given: true,
    raw_submission: { community: "Apt 0815" },
  },
  // Remaining 5 prospects — not on wellness watch
  {
    id: "demo-prospect-009",
    created_at: "2026-06-08T11:00:00Z",
    status: "reviewing",
    source: "community_liaison",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Harold",
    resident_last_name: "Bennett",
    resident_relationship: "parent",
    contact_first_name: "Nancy",
    contact_last_name: "Bennett",
    contact_phone: "(469) 555-0204",
    contact_email: null,
    support_type: "home_care",
    start_timing: "coming_weeks",
    care_needs: null,
    referral_source: "staff_referral",
    consent_given: true,
    raw_submission: { community: "Apt 3210" },
  },
  {
    id: "demo-prospect-010",
    created_at: "2026-06-05T14:00:00Z",
    status: "new",
    source: "website",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Roger",
    resident_last_name: "Callahan",
    resident_relationship: "spouse",
    contact_first_name: "Mary",
    contact_last_name: "Callahan",
    contact_phone: "(214) 555-0589",
    contact_email: "m.callahan@email.com",
    support_type: "concierge",
    start_timing: "coming_weeks",
    care_needs: null,
    referral_source: "family_referral",
    consent_given: true,
    raw_submission: { community: "Apt 4102" },
  },
  {
    id: "demo-prospect-011",
    created_at: "2026-05-28T10:30:00Z",
    status: "new",
    source: "community_liaison",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Beatrice",
    resident_last_name: "Harmon",
    resident_relationship: "parent",
    contact_first_name: "William",
    contact_last_name: "Harmon",
    contact_phone: "(972) 555-0837",
    contact_email: null,
    support_type: "home_care",
    start_timing: "future",
    care_needs: null,
    referral_source: null,
    consent_given: false,
    raw_submission: { community: "Apt 0310" },
  },
  {
    id: "demo-prospect-012",
    created_at: "2026-06-01T09:00:00Z",
    status: "new",
    source: "website",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Clarence",
    resident_last_name: "Webb",
    resident_relationship: "parent",
    contact_first_name: "Linda",
    contact_last_name: "Webb",
    contact_phone: "(469) 555-0416",
    contact_email: null,
    support_type: "not_sure",
    start_timing: "not_sure",
    care_needs: null,
    referral_source: null,
    consent_given: true,
    raw_submission: { community: "Apt 2730" },
  },
  {
    id: "demo-prospect-013",
    created_at: "2026-06-19T16:00:00Z",
    status: "contacted",
    source: "community_liaison",
    inquiry_type: "care_for_resident",
    zip_code: "75034",
    resident_first_name: "Evelyn",
    resident_last_name: "Marsh",
    resident_relationship: "parent",
    contact_first_name: "Joseph",
    contact_last_name: "Marsh",
    contact_phone: "(214) 555-0753",
    contact_email: "j.marsh@email.com",
    support_type: "geriatric",
    start_timing: "coming_weeks",
    care_needs:
      "Evelyn's family is planning for increased care needs following a recent hospitalization. Her son Joseph is the primary decision-maker and point of contact.",
    referral_source: "doctor_referral",
    consent_given: true,
    raw_submission: { community: "Apt 1118" },
  },
];
