// AUTO-GENERATED by scripts/generate-deploy-context.mjs at build time — do not edit by hand.
// Regenerated on every `npm run build` from Netlify's BUILD-time-only DEPLOY_PRIME_URL/CONTEXT
// env vars. Committed here with null defaults for local/dev runs (a plain `next build` on a
// laptop, or this test suite, never regenerates this file), where every value below is genuinely
// absent — see resolveSiteBaseUrl() in pipeline.ts for why that must mean "fail closed," not
// "fall back to something else."
//
// WHY a generated file instead of just reading process.env at runtime: Netlify's own docs
// confirm only URL, SITE_NAME, and SITE_ID are automatically forwarded into a Netlify Function's
// RUNTIME process.env — DEPLOY_PRIME_URL and CONTEXT are build-time-only and are simply absent
// by the time any Function (Scheduled, Background, or the Next.js Runtime's own Server Action
// handler) actually runs. And URL alone is not safe to use for this purpose: it is always the
// site's PRODUCTION address regardless of deploy context — a Deploy Preview or branch-deploy
// dispatcher that fell back to it would silently invoke production's background worker instead
// of its own (production may not even have this feature yet). This file captures the correct
// value once, at build time, so it survives into runtime as a literal instead of being guessed.
export interface GeneratedDeployContext {
  context: string | null;
  deployPrimeUrl: string | null;
}

export const GENERATED_DEPLOY_CONTEXT: GeneratedDeployContext = {
  "context": null,
  "deployPrimeUrl": null
};
