// AUTO-GENERATED by scripts/generate-deploy-context.mjs at build time — do not edit by hand.
// Regenerated on every `npm run build` from Netlify's BUILD-time-only DEPLOY_PRIME_URL/CONTEXT/URL
// env vars. Committed here with null defaults for local/dev runs (a plain `next build` on a
// laptop, or this test suite, never regenerates this file), where every value below is genuinely
// absent — see resolveSiteBaseUrl() in pipeline.ts for why that must mean "fail closed," not "fall
// back to something else."
//
// WHY a generated file instead of just reading process.env at runtime: confirmed directly against
// Netlify's own docs (https://docs.netlify.com/build/functions/environment-variables/) that only
// URL, SITE_NAME, and SITE_ID are automatically forwarded into a Netlify Function's RUNTIME
// process.env — DEPLOY_PRIME_URL and CONTEXT are build-time-only and are simply absent by the time
// any Function (Scheduled, Background, or the Next.js Runtime's own Server Action handler) actually
// runs. The Netlify Function `Context` object (the second handler argument) doesn't fill this gap
// either — confirmed via Netlify's Functions API docs that `context.site.url` is the production URL
// only, and `context.deploy` carries no URL field at all. So the ONLY point at which
// DEPLOY_PRIME_URL/CONTEXT are ever actually available is during the build step itself — this file
// captures them then, once, so the correct value survives into runtime as a literal.
export interface GeneratedDeployContext {
  context: string | null;
  deployPrimeUrl: string | null;
  url: string | null;
}

export const GENERATED_DEPLOY_CONTEXT: GeneratedDeployContext = {
  "context": null,
  "deployPrimeUrl": null,
  "url": null
};
